/**
 * HTML renderer with folder icons and domain subfolders.
 */

import type { Bookmark } from "./parser.js";
import { getFolderIcon } from "./icons.js";
import { domainOf } from "./classifier.js";

export interface TreeNode {
  title: string;
  children: Map<string, TreeNode>;
  links: Bookmark[];
}

export function createTree(): TreeNode {
  return { title: "ROOT", children: new Map(), links: [] };
}

export function addBookmark(root: TreeNode, path: string, bm: Bookmark, titleOverride?: string): void {
  const parts = path.split("/");
  let node = root;
  for (const part of parts) {
    if (!node.children.has(part)) {
      node.children.set(part, { title: part, children: new Map(), links: [] });
    }
    node = node.children.get(part)!;
  }
  const entry = { ...bm };
  if (titleOverride !== undefined) (entry as any).renderTitle = titleOverride;
  node.links.push(entry);
}

/**
 * Add domain subfolders within leaf nodes that have 3+ bookmarks from the same domain.
 */
function isDomainFolderName(title: string): boolean {
  return /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$/i.test(title);
}

/**
 * Move direct bookmarks in leaf folders into website/domain subfolders.
 *
 * This is intentionally leaf-only so taxonomy folders such as
 * `#__AI/##OPEN_SOURCE/###MCP_SERVERS` become:
 * `###MCP_SERVERS/github.com/<bookmarks>` rather than grouping at higher levels.
 */
export function groupByDomain(node: TreeNode, insideDomainFolder = false, minTotal = 6, minDomain = 3): void {
  if (!insideDomainFolder && node.children.size === 0 && node.links.length >= minTotal) {
    const byDomain = new Map<string, Bookmark[]>();
    for (const bm of node.links) {
      const d = domainOf(bm.url);
      if (!d) continue;
      if (!byDomain.has(d)) byDomain.set(d, []);
      byDomain.get(d)!.push(bm);
    }

    const grouped = [...byDomain.entries()].filter(([, bookmarks]) => bookmarks.length >= minDomain);

    if (grouped.length > 0) {
      const groupedDomains = new Set(grouped.map(([domain]) => domain));
      const remaining: Bookmark[] = [];
      for (const bm of node.links) {
        const d = domainOf(bm.url);
        if (!groupedDomains.has(d)) remaining.push(bm);
      }
      node.links = remaining;
      for (const [d, bookmarks] of grouped) {
        node.children.set(d, { title: d, children: new Map(), links: bookmarks });
      }
    }
  }

  for (const child of node.children.values()) {
    groupByDomain(child, insideDomainFolder || isDomainFolderName(child.title), minTotal, minDomain);
  }
}

export function sortTree(node: TreeNode): void {
  node.links.sort((a, b) => {
    const ta = (((a as any).renderTitle ?? a.title) || "").toLowerCase();
    const tb = (((b as any).renderTitle ?? b.title) || "").toLowerCase();
    return ta.localeCompare(tb);
  });
  for (const child of node.children.values()) {
    sortTree(child);
  }

  node.children = new Map([...node.children.entries()].sort(([a], [b]) => a.localeCompare(b)));
}

function escapeHtml(text: string): string {
  return (text || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderNode(node: TreeNode, indent: number, now: number, specialBar = false): string[] {
  const sp = "    ".repeat(indent);
  const lines: string[] = [];

  for (const [title, child] of node.children) {
    const icon = getFolderIcon(title);
    const iconAttr = ` ICON="${icon}"`;
    const toolbarAttr = specialBar && title === "Bookmarks bar" ? ' PERSONAL_TOOLBAR_FOLDER="true"' : "";
    const attrs = ` ADD_DATE="${now}"${iconAttr}${toolbarAttr}`;
    lines.push(`${sp}<DT><H3${attrs}>${escapeHtml(title)}</H3>`);
    lines.push(`${sp}<DL><p>`);

    for (const bm of child.links) {
      const renderTitle = (bm as any).renderTitle ?? bm.title;
      const iconAttr = bm.icon ? ` ICON="${bm.icon}"` : "";
      const dateAttr = ` ADD_DATE="${bm.addDate || now}"`;
      lines.push(`${sp}    <DT><A HREF="${escapeHtml(bm.url)}"${dateAttr}${iconAttr}>${escapeHtml(renderTitle)}</A>`);
    }

    lines.push(...renderNode(child, indent + 1, now, false));
    lines.push(`${sp}</DL><p>`);
  }

  return lines;
}

export function renderHtml(root: TreeNode): string {
  const now = Math.floor(Date.now() / 1000);
  const lines = [
    "<!DOCTYPE NETSCAPE-Bookmark-file-1>",
    "<!-- Automatically generated by bookmark-mcp -->",
    '<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">',
    "<TITLE>Bookmarks</TITLE>",
    "<H1>Bookmarks</H1>",
    "<DL><p>",
  ];
  lines.push(...renderNode(root, 1, now, true));
  lines.push("</DL><p>");
  return lines.join("\n");
}
